### ISSUE TITLE
App paniked on "Select Directory" button press 

### ISSUE THREAD

**Issue by JorgenPo** [tbillington/kondo#31] opened 2021-01-20 11:25 UTC
OS: Linux Kubuntu 18.04
Kernel: 4.15.0-128-generic
AppVersion: 0.1.0 (the last from Cargo)

Terminal output (verbose):
```
popov@popov ~> env RUST_BACKTRACE=1 RUST_BACKTRACE=full /home/popov/.cargo/bin/kondo-ui
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
thread 'main' panicked at 'already borrowed: BorrowMutError', /home/popov/.cargo/registry/src/github.com-1ecc6299db9ec823/druid-shell-0.5.0/src/platform/gtk/window.rs:345:22
stack backtrace:
   0:     0x558f6fa08355 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x558f6fa08355 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x558f6fa08355 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x558f6fa08355 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x558f6f9cfe9c - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x558f6fa079b6 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x558f6fa07340 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x558f6fa07340 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x558f6fa07340 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x558f6fa06a53 - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x558f6fa06a53 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x558f6fa066f8 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x558f6fa066c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x558f6fa0667d - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x558f6f9ce240 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x558f6f9d1082 - core::option::expect_none_failed::h448b58a024c2c33a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
  16:     0x558f6f9e8253 - core::cell::RefCell<T>::borrow_mut::h3603befb390e1563
  17:     0x558f6f9e97b1 - <O as gtk::auto::widget::WidgetExt>::connect_leave_notify_event::leave_notify_event_trampoline::h75875ed0bb521cbe
  18:     0x7f6e198508f7 - <unknown>
  19:     0x7f6e18a29346 - <unknown>
  20:     0x7f6e18a443cd - g_signal_emit_valist
  21:     0x7f6e18a4512f - g_signal_emit
  22:     0x7f6e19998534 - <unknown>
  23:     0x7f6e1999883d - <unknown>
  24:     0x7f6e1999e707 - <unknown>
  25:     0x7f6e1984da30 - <unknown>
  26:     0x7f6e1984dd30 - <unknown>
  27:     0x7f6e1973f3d0 - <unknown>
  28:     0x7f6e1984dc01 - <unknown>
  29:     0x7f6e199ad4c9 - <unknown>
  30:     0x7f6e1984dc01 - <unknown>
  31:     0x7f6e1984dea7 - <unknown>
  32:     0x7f6e18a2910d - g_closure_invoke
  33:     0x7f6e18a3c12e - <unknown>
  34:     0x7f6e18a44715 - g_signal_emit_valist
  35:     0x7f6e18a4512f - g_signal_emit
  36:     0x7f6e199a10c6 - gtk_widget_show
  37:     0x7f6e19879e20 - gtk_native_dialog_show
  38:     0x7f6e1987a5fa - gtk_native_dialog_run
  39:     0x558f6f9ebd6f - druid_shell::platform::gtk::window::WindowHandle::file_dialog::h61890d67b1dfd6d5
  40:     0x558f6f9ba465 - druid::win_handler::AppState<T>::handle_cmd::hc2abc37aad9a458d
  41:     0x558f6f9bab2f - druid::win_handler::AppState<T>::process_commands::h088db73c09277ecc
  42:     0x558f6f9baa1e - druid::win_handler::AppState<T>::do_window_event::h72282a694bc2956c
  43:     0x558f6f9c5125 - <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::mouse_up::h6dea4b8b5390d8cc
  44:     0x558f6f9e9a31 - <O as gtk::auto::widget::WidgetExt>::connect_button_release_event::button_release_event_trampoline::h50bb8aa8b40ec165
  45:     0x7f6e198507fb - <unknown>
  46:     0x7f6e18a2910d - g_closure_invoke
  47:     0x7f6e18a3c05e - <unknown>
  48:     0x7f6e18a440af - g_signal_emit_valist
  49:     0x7f6e18a4512f - g_signal_emit
  50:     0x7f6e19998534 - <unknown>
  51:     0x7f6e1984d86e - <unknown>
  52:     0x7f6e1984f948 - gtk_main_do_event
  53:     0x7f6e19360765 - <unknown>
  54:     0x7f6e19390f92 - <unknown>
  55:     0x7f6e1874e417 - g_main_context_dispatch
  56:     0x7f6e1874e650 - <unknown>
  57:     0x7f6e1874e6dc - g_main_context_iteration
  58:     0x7f6e18d0fefd - g_application_run
  59:     0x558f6f9cb2d0 - kondo_ui::main::h725d4d5bbde190fc
  60:     0x558f6f9b314c - std::sys_common::backtrace::__rust_begin_short_backtrace::h4fefc5af64538c72
  61:     0x558f6f9cca0b - main
  62:     0x7f6e17aefbf7 - __libc_start_main
  63:     0x558f6f9ad3ea - _start
  64:                0x0 - <unknown>
```

**Comment by tbillington** [comment] 2021-01-20 22:46
Oh nice! Thanks for the report :)

I have a ubuntu 20.10 I'll try to reproduce on.

Do you know if this happen consistently, or just once ?

**Comment by JorgenPo** [comment] 2021-01-23 10:44
This happens every time I try to press the button

**Comment by tbillington** [comment] 2021-01-31 22:53
Going to try bump the rendering library being used (druid) and see if that helps. If it doesn't I don't think there'd be much I can do unfortunately, the issue would be upstream and I haven't been able to replicate it on my computer.

**Comment by JorgenPo** [comment] 2021-02-02 09:40
I've tried to compile the app from sources and the file dialog works perfect. The problem only appears on cargo crate

**Comment by tbillington** [comment] 2021-02-17 09:57
Okay, I think publishing the current version would fix your issue of installing from crates then. I think the current published version in a bit behind for the UI library (druid).

**Comment by tbillington** [comment] 2021-03-28 03:24
@JorgenPo I've published kondo-ui .2 on crates, installing from cargo should work now!

**Comment by tbillington** [comment] 2021-06-03 23:29
I'm going to close this since I _think_ it's fixed. Feel free to raise another issue if it persists :)

**Closed by tbillington** 2021-06-03 23:29 UTC
